image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-voting-microservice:
  stage: build
  script:
    gradle Code:voting-microservice:assemble Code:voting-microservice:testClasses

checkStyle-voting-microservice:
  stage: staticAnalysis
  script:
    gradle Code:voting-microservice:checkstyleMain Code:voting-microservice:checkStyleTest
  allow_failure: true


PMD-voting-microservice:
  stage: staticAnalysis
  script:
    gradle Code:voting-microservice:pmdMain
  allow_failure: true

test-voting-microservice:
  stage: test
  script:
    - gradle Code:voting-microservice:test Code:voting-microservice:jacocoTestReport
    - cat Code/voting-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
