image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-hoa-microservice:
  stage: build
  script:
    gradle Code:hoa-microservice:assemble Code:hoa-microservice:testClasses

checkStyle-hoa-microservice:
  stage: staticAnalysis
  script:
    gradle Code:hoa-microservice:checkstyleMain Code:hoa-microservice:checkStyleTest
  allow_failure: true


PMD-hoa-microservice:
  stage: staticAnalysis
  script:
    gradle Code:hoa-microservice:pmdMain
  allow_failure: true

test-hoa-microservice:
  stage: test
  script:
    - gradle Code:hoa-microservice:test Code:hoa-microservice:jacocoTestReport
    - cat Code/hoa-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
